LOCATIONS = {
    'Ernakulam': ['Ernakulam District', 'Ernakulam Town', 'Marine Drive', 'Hill Palace Museum', 'Dutch Cemetery', 'LuLu Mall', 'Jawaharlal Nehru International Stadium', 'Mangalavanam Bird Sanctuary', 'Veegaland Waterpark', 'Wonder La Amusement Park'],
    'Fort Kochi': ['Bastion Bungalow', 'Fort Kochi', 'Santa Cruz Basilica', 'Dutch Palace', 'Jewish Synagogue', 'Chinese Fishing Nets', 'Aspinwall House'],
    'Mattancherry': ['Mattancherry Palace', 'Dutch Cemetery', 'Spice Market'],
    'Cherai Beach': ['Cherai Beach', 'Cherai Beach Resort'],
    'Munnar': ['Munnar', 'Eravikulam National Park', 'Tea Gardens', 'Mattupetty Dam', 'Echo Point'],
    'Thekkady': ['Periyar National Park', 'Periyar Tiger Trail', 'Spice Gardens', 'Elephant Junction'],
    'Athirappilly': ['Athirappilly Waterfalls', 'Vazhachal Waterfalls'],
    'Kumarakom': ['Kumarakom Bird Sanctuary', 'Vembanad Lake', 'Backwaters', 'Pathiramanal Island'],
    'Marari Beach': ['Marari Beach', 'Marari Beach Resort'],
    'Alappuzha': ['Alappuzha Beach', 'Backwaters', 'Houseboats', 'Nehru Trophy Boat Race'],
    'Thrissur': ['Vadakkunnathan Temple', 'Thrissur Pooram', 'Archaeological Museum'],
    'Kottayam': ['Kumaranalloor', 'Kumarakom Bird Sanctuary', 'Vembanad Lake'],
    'Idukki': ['Idukki Wildlife Sanctuary', 'Meesapulimala', 'Kalvari Mount', 'Idukki Dam'],
    'Kochi': ['Kochi Marina', 'Mattancherry Palace', 'Fort Kochi Beach', 'Chinese Fishing Nets', 'Jew Town', 'Bolgatty Palace', 'Veeranpuzha Beach', 'Princess Street', 'Willingdon Island'],
    'Ernakulam District': ['Ernakulam', 'Fort Kochi', 'Mattancherry', 'Cherai Beach', 'Munnar', 'Thekkady', 'Athirappilly', 'Kumarakom', 'Marari Beach', 'Alappuzha', 'Thrissur', 'Kottayam', 'Idukki'],
    'Aliveenakuthu Waterfalls': ['Aliveenakuthu Waterfalls'],
    'Aanachal Kadavu': ['Aanachal Kadavu'],
    'Abhayaranyam Kaprikkad Ecotourism': ['Abhayaranyam', 'Abhayaranyam Kaprikkad Ecotourism'],
    'Adi Shankara Sthoopam Temple': ['Adi Shankara Sthoopam', 'Adi Shankara Sthoopam Temple'],
    'Alangad': ['Alangad'],
    'Aluva': ['Aluva Sivarathri Manappuram', 'Aluva Palace', 'Aluva Shiva Temple'],
    'Aluva Sivarathri Manappuram': ['Aluva Sivarathri Manappuram'],
    'Ameda Temple': ['Ameda Temple', 'Ameda Nagaraja Temple'],
    'Anchumana Devi Temple': ['Anchumana Devi Temple'],
    'Andhakaranazhi Beach': ['Andhakaranazhi Beach'],
    'Angamaly': ['Angamaly'],
    'Areekkal Waterfalls': ['Areekkal Waterfalls'],
    'Aroor': ['Aroor'],
    'Aspinwall House': ['Aspinwall House'],
    'Attayam Chira': ['Attayam Chira'],
    'Attutheeram River View': ['Attutheeram River View'],
    'Ayyappanmudi': ['Ayyappanmudi', 'Mount Ayyappan'],
    'Basilica of Our Lady of Ransom Vallarpadam': ['Basilica of Our Lady of Ransom Vallarpadam', 'Vallarpadam Basilica'],
    'Bhoothathankettu': ['Bhoothathankettu'],
    'Bhoothathankettu Dam': ['Bhoothathankettu Dam'],
    'Bishop\'s House Kochi': ['Bishop\'s House Kochi'],
    'Bolgatty Palace': ['Bolgatty Palace'],
    'Broadway Ernakulam': ['Broadway Ernakulam'],
    'Centre Square Mall': ['Centre Square Mall'],
    'Chakki Para View Point': ['Chakki Para View Point'],
    'Chellanam Beach': ['Chellanam Beach'],
    'Chendamangalam': ['Chendamangalam'],
    'Cherai': ['Cherai'],
    'Cherai Beach': ['Cherai Beach'],
    'Cheranallur': ['Cheranallur'],
    'Cheranelloor': ['Cheranelloor'],
    'Chinese Fishing Nets': ['Chinese Fishing Nets'],
    'Chittoor': ['Chittoor'],
    'Chottanikkara Devi Temple': ['Chottanikkara Devi Temple'],
    'Cochin Port Maritime Heritage Museum': ['Cochin Port Maritime Heritage Museum'],
    'Cochin Shipyard': ['Cochin Shipyard'],
    'Copt Avenue Walkway': ['Copt Avenue Walkway'],
    'Dutch Palace': ['Dutch Palace'],
    'Edapally': ['Edapally'],
    'Edappally Church': ['Edappally Church'],
    'Edayan Lake': ['Edayan Lake'],
    'Elamakkara': ['Elamakkara'],
    'Elamkunnapuzha Beach': ['Elamkunnapuzha Beach'],
    'Eloor': ['Eloor'],
    'Erappu Waterfalls': ['Erappu Waterfalls'],
    'Ernakulam': ['Ernakulam'],
    'Ernakulam Shiva Temple': ['Ernakulam Shiva Temple'],
    'Ezhattumugham Waterfalls': ['Ezhattumugham Waterfalls'],
    'Falcon Beach': ['Falcon Beach'],
    'Fort Emmanuel': ['Fort Emmanuel'],
    'Fort Kochi': ['Fort Kochi'],
    'Fort Kochi Beach': ['Fort Kochi Beach'],
    'Forum Mall Kochi': ['Forum Mall Kochi'],
    'Grey Book Museum': ['Grey Book Museum'],
    'Hidumban Mala': ['Hidumban Mala'],
    'Hill Palace Museum': ['Hill Palace Museum'],
    'Illithode Waterfalls': ['Illithode Waterfalls'],
    'Inchathotty Suspension Bridge': ['Inchathotty Suspension Bridge'],
    'Indian Naval Maritime Museum': ['Indian Naval Maritime Museum'],
    'Indo-Portuguese Museum': ['Indo-Portuguese Museum'],
    'Infopark Kochi': ['Infopark Kochi'],
    'Iringole Kavu Temple': ['Iringole Kavu Temple'],
    'Jain Temple': ['Jain Temple'],
    'Jawaharlal Nehru Stadium': ['Jawaharlal Nehru Stadium'],

    'Jew Street Mattancherry': ['Jew Street Mattancherry'],
    'Jew Town': ['Jew Town'],
    'Jewish Synagogue': ['Jewish Synagogue'],
    'Kadamakkudy Islands': ['Kadamakkudy Islands'],
    'Kadamattom Church': ['Kadamattom Church'],
    'Kadambrayar': ['Kadambrayar'],
    'Kadavanthra': ['Kadavanthra'],
    'Kakkanad': ['Kakkanad'],
    'Kakkanadu East': ['Kakkanadu East'],
    'Kakkanadu West': ['Kakkanadu West'],
    'Kakkante Mala': ['Kakkante Mala'],
    'Kalady': ['Kalady'],
    'Kalamassery': ['Kalamassery'],
    'Kaloor': ['Kaloor'],
    'Kamalakadavu Fort Kochi': ['Kamalakadavu Fort Kochi'],
    'Kandakkadavu View Point': ['Kandakkadavu View Point'],
    'Kanjiramattom Mosque': ['Kanjiramattom Mosque'],
    'Kerala Folklore Museum': ['Kerala Folklore Museum'],
    'Kerala Kathakali Centre': ['Kerala Kathakali Centre'],
    'Kettezhthum Kadavu': ['Kettezhthum Kadavu'],
    'Kizhakkambalam': ['Kizhakkambalam'],
    'Kizhakombu Kavu': ['Kizhakombu Kavu'],
    'Kochareekkal Caves': ['Kochareekkal Caves'],
    'Kochi Biennale': ['Kochi Biennale'],
    'Kochi Metro': ['Kochi Metro'],
    'Kochi Water Metro': ['Kochi Water Metro'],
    'Kodanad Elephant Training Centre': ['Kodanad Elephant Training Centre'],
    'Kodikuthimala': ['Kodikuthimala'],
    'Koonankurishu Church': ['Koonankurishu Church'],
    'Koorumala': ['Koorumala'],
    'Kothamangalam': ['Kothamangalam'],
    'Kulippara Waterfalls': ['Kulippara Waterfalls'],
    'Kumbalam': ['Kumbalam'],
    'Kumbalanghi': ['Kumbalanghi'],
    'Kundannoor': ['Kundannoor'],
    'Kuttippara Waterfalls': ['Kuttippara Waterfalls'],
    'Kuzhuppilly Beach': ['Kuzhuppilly Beach'],
    'Lazza iDrive': ['Lazza iDrive'],
    'Little Flower Church': ['Little Flower Church'],
    'LuLu Mall': ['LuLu Mall'],
    'Malayattoor Church': ['Malayattoor Church'],
    'Mamalakandam View Point': ['Mamalakandam View Point'],
    'Manappattu Chira': ['Manappattu Chira'],
    'Mangalathu Kavu Bhagavathi Temple': ['Mangalathu Kavu Bhagavathi Temple'],
    'Mangalavanam Bird Sanctuary': ['Mangalavanam Bird Sanctuary'],
    'Maniyanthiram Hill Top': ['Maniyanthiram Hill Top'],
    'Maradu': ['Maradu'],
    'Marine Drive': ['Marine Drive'],
    'Marottichuvadu Waterfalls': ['Marottichuvadu Waterfalls'],
    'Mattancherry': ['Mattancherry'],
    'Mattancherry Palace': ['Mattancherry Palace'],
    'Meekunnam Waterfalls': ['Meekunnam Waterfalls'],
    'Moolampilly Islands': ['Moolampilly Islands'],
    'Mulavukad': ['Mulavukad'],
    'Munambam Beach': ['Munambam Beach'],
    'Munippara Waterfalls': ['Munippara Waterfalls'],
    'Muniyara Cave': ['Muniyara Cave'],
    'Museum of Kerala History': ['Museum of Kerala History'],
    'Muvattupuzha': ['Muvattupuzha'],
    'Nadukani View Point': ['Nadukani View Point'],
    'Nakshathra Vanam': ['Nakshathra Vanam'],
    'National Marine Biodiversity Museum': ['National Marine Biodiversity Museum'],
    'Nedumbassery': ['Nedumbassery'],
    'Nettoor': ['Nettoor'],
    'Njarackal Arattuvazhi Beach': ['Njarackal Arattuvazhi Beach'],
    'North Paravur': ['North Paravur'],
    'Ooranattu Chira': ['Ooranattu Chira'],
    'Pachalam': ['Pachalam'],
    'Padivattom': ['Padivattom'],
    'Palarivattom': ['Palarivattom'],
    'Palliam Palace': ['Palliam Palace'],
    'Pallikara': ['Pallikara'],
    'Pallikkara Church': ['Pallikkara Church'],
    'Pallipuram Fort': ['Pallipuram Fort'],
    'Palluruthy': ['Palluruthy'],
    'Panampilly Nagar': ['Panampilly Nagar'],
    'Panampilly Nagar Central Park': ['Panampilly Nagar Central Park'],
    'Panangad': ['Panangad'],
    'Panangad Jetty': ['Panangad Jetty'],
    'Paniyeli Poru': ['Paniyeli Poru'],
    'Paradesi Synagogue': ['Paradesi Synagogue'],
    'Paravur': ['Paravur'],
    'Parikshit Thampuram Museum': ['Parikshit Thampuram Museum'],
    'Pavamkulangara Devi Temple': ['Pavamkulangara Devi Temple'],
    'Pazhangad Beach': ['Pazhangad Beach'],
    'Pazhoor': ['Pazhoor'],
    'Peechattu Mala': ['Peechattu Mala'],
    'Periyar Lake': ['Periyar Lake'],
    'Periyar Wildlife Sanctuary': ['Periyar Wildlife Sanctuary'],
    'Perumbavoor': ['Perumbavoor'],
    'Pettamala': ['Pettamala'],
    'Pindimedu Waterfalls': ['Pindimedu Waterfalls'],
    'Poonithura': ['Poonithura'],
    'Puliyanipara View Point': ['Puliyanipara View Point'],
    'Puliyanpara View Point': ['Puliyanpara View Point'],
    'Puthenthode Beach': ['Puthenthode Beach'],
    'Puthenvelikkara': ['Puthenvelikkara'],
    'Puthuvype Beach': ['Puthuvype Beach'],
    'Puthuvype Lighthouse Beach': ['Puthuvype Lighthouse Beach'],
    'Queens Walkway': ['Queens Walkway'],
    'Rainbow Hanging Bridge': ['Rainbow Hanging Bridge'],
    'Rosary Park Vallarpadam': ['Rosary Park Vallarpadam'],
    'Santa Cruz Cathedral Basilica': ['Santa Cruz Cathedral Basilica'],
    'Science Park Kalamassery': ['Science Park Kalamassery'],
    'Shoolam Waterfalls': ['Shoolam Waterfalls'],
    'Sree Murugan Temple': ['Sree Murugan Temple'],
    'Sree Poornathrayeesa Temple': ['Sree Poornathrayeesa Temple'],
    'Sreekrishna Swamy Temple': ['Sreekrishna Swamy Temple'],
    'St. Francis Church': ['St. Francis Church'],
    'Streetscape Panampilly Nagar': ['Streetscape Panampilly Nagar'],
    'Subhash Bose Park': ['Subhash Bose Park'],
    'Synodal Museum': ['Synodal Museum'],
    'Thamaramkulangara Temple': ['Thamaramkulangara Temple'],
    'Thammanam': ['Thammanam'],
    'Thattekkadu Bird Sanctuary': ['Thattekkadu Bird Sanctuary'],
    'Thattekkadu': ['Thattekkadu'],
    'Thevara Ferry View Point': ['Thevara Ferry View Point'],
    'Thirubali Waterfalls': ['Thirubali Waterfalls'],
    'Thiruvankulam': ['Thiruvankulam'],
    'Thonippara Waterfalls': ['Thonippara Waterfalls'],
    'Thoppumpady': ['Thoppumpady'],
    'Thrikkakara': ['Thrikkakara'],
    'Thrikkakara Temple': ['Thrikkakara Temple'],
    'Thrikkariyoor Temple': ['Thrikkariyoor Temple'],
    'Tripunithura': ['Tripunithura'],
    'Triveni Sangamam': ['Triveni Sangamam'],
    'Vadattupara Waterfalls': ['Vadattupara Waterfalls'],
    'Vaduthala': ['Vaduthala'],
    'Vaikom Mahadeva Temple': ['Vaikom Mahadeva Temple'],
    'Valanthakad River Drive': ['Valanthakad River Drive'],
    'Valappu Beach': ['Valappu Beach'],
    'Valiyavattom Island': ['Valiyavattom Island'],
    'Vallarpadam Church': ['Vallarpadam Church'],
    'Vandambra Para': ['Vandambra Para'],
    'Varapuzha': ['Varapuzha'],
    'Vasco da Gama Square': ['Vasco da Gama Square'],
    'Vazhachal Waterfalls': ['Vazhachal Waterfalls'],
    'Vazhakkulam': ['Vazhakkulam'],
    'Veeranpuzha': ['Veeranpuzha'],
    'vennala': ['vennala'],
    'vypin': ['vypin beach'],
    'vytilla': ['vytilla'],
    'willingdon island': ['willingdon island']
    
}