LOCATIONS = {
    'Ernakulam': ['Ernakulam District', 'Ernakulam Town', 'Marine Drive', 'Hill Palace Museum', 'Dutch Cemetery', 'LuLu Mall', 'Jawaharlal Nehru International Stadium', 'Mangalavanam Bird Sanctuary', 'Veegaland Waterpark', 'Wonder La Amusement Park'],
    'Fort Kochi': ['Fort Kochi', 'Santa Cruz Basilica', 'Dutch Palace', 'Jewish Synagogue', 'Chinese Fishing Nets'],
    'Mattancherry': ['Mattancherry Palace', 'Dutch Cemetery', 'Spice Market'],
    'Cherai Beach': ['Cherai Beach', 'Cherai Beach Resort'],
    'Munnar': ['Munnar', 'Eravikulam National Park', 'Tea Gardens', 'Mattupetty Dam', 'Echo Point'],
    'Thekkady': ['Periyar National Park', 'Periyar Tiger Trail', 'Spice Gardens', 'Elephant Junction'],
    'Athirappilly': ['Athirappilly Waterfalls', 'Vazhachal Waterfalls'],
    'Kumarakom': ['Kumarakom Bird Sanctuary', 'Vembanad Lake', 'Backwaters', 'Pathiramanal Island'],
    'Marari Beach': ['Marari Beach', 'Marari Beach Resort'],
    'Alappuzha': ['Alappuzha Beach', 'Backwaters', 'Houseboats', 'Nehru Trophy Boat Race'],
    'Thrissur': ['Vadakkunnathan Temple', 'Thrissur Pooram', 'Archaeological Museum'],
    'Kottayam': ['Kumaranalloor', 'Kumarakom Bird Sanctuary', 'Vembanad Lake'],
    'Idukki': ['Idukki Wildlife Sanctuary', 'Meesapulimala', 'Kalvari Mount', 'Idukki Dam'],
    'Kochi': ['Kochi Marina', 'Mattancherry Palace', 'Fort Kochi Beach', 'Chinese Fishing Nets', 'Jew Town', 'Bolgatty Palace', 'Veeranpuzha Beach', 'Princess Street', 'Willingdon Island'],
    'Ernakulam District': ['Ernakulam', 'Fort Kochi', 'Mattancherry', 'Cherai Beach', 'Munnar', 'Thekkady', 'Athirappilly', 'Kumarakom', 'Marari Beach', 'Alappuzha', 'Thrissur', 'Kottayam', 'Idukki'],
    'Aaliveenakuthu Waterfalls': [],
    'Aanachal Kadavu': [],
    'Abhayaranyam Kaprikkadu Ecotourism': [],
    'Adi Shankara Sthoopam Temple': [],
    'Alangad': [],
    'Aluva': [],
    'Aluva Sivarathri Manappuram': [],
    'Ameda Temple': [],
    'Anchumana Devi Temple': [],
    'Andhakaranazhi Beach': [],
    'Angamaly': [],
    'Areekkal Waterfalls': [],
    'Aroor': [],
    'Aspinwall House': [],
    'Athirappally Waterfalls': [],
    'Attayam Chira': [],
    'Attutheeram River View': [],
    'Ayyappanmudi': [],
    'Backwaters of Kochi': [],
    'Basilica of Our Lady of Ransom Vallarpadam': [],
    'Bastion Bunglow': [],
    'Bhoothathankettu': [],
    'Bhoothathankettu Dam': [],
    'Bishop\'s House Kochi': [],
    'Bolgatty Palace': [],
    'Broadway Ernakulam': [],
    'Centre Square Mall': [],
    'Chakki Para View Point': [],
    'Chellanam Beach': [],
    'Chendamangalam': [],
    'Cherai': [],
    'Cherai Beach': [],
    'Cheranallur': [],
    'Cheranelloor': [],
    'Chinese Fishing Nets': [],
    'Chittoor': [],
    'Chottanikkara Devi Temple': [],
    'Cochin Port Maritime Heritage Museum': [],
    'Cochin Shipyard': [],
    'Copt Avenue Walkway': [],
    'Dutch Palace': [],
    'Edapally': [],
    'Edappally Church': [],
    'Edayan Lake': [],
    'Elamakkara': [],
    'Elamkunnapuzha Beach': [],
    'Eloor': [],
    'Erappu Waterfalls': [],
    'Falcon Beach': [],
    'Fort Emmanuel': [],
    'Fort Kochi': [],
    'Fort Kochi Beach': [],
    'Forum Mall Kochi': [],
    'Grey Book Museum': [],
    'Hidumban Mala': [],
    'Hill Palace Museum': [],
    'Illithode Waterfalls': [],
    'Inchathotty Suspension Bridge': [],
    'Indian Naval Maritime Museum': [],
    'Indo-Portuguese Museum': [],
    'Infopark Kochi': [],
    'Iringole Kavu Temple': [],
    'Jain Temple': [],
    'Jawaharlal Nehru Stadium': [],
    'Jew Street Mattancherry': [],
    'Jew Town': [],
    'Jewish Synagogue': [],
    'Kadamakkudy Islands': [],
    'Kadamattom Church': [],
    'Kadambrayar': [],
    'Kadavanthra': [],
    'Kakkanad': [],
    'Kakkanadu East': [],
    'Kakkanadu West': [],
    'Kakkante Mala': [],
    'Kalady': [],
    'Kalamassery': [],
    'Kaloor': [],
    'Kamalakadavu Fort Kochi': [],
    'Kandakkadavu View Point': [],
    'Kanjiramattom Mosque': [],
    'Kerala Folklore Museum': [],
    'Kerala Kathakali Centre': [],
    'Kettezhthum Kadavu': [],
    'Kizhakkambalam': [],
    'Kizhakombu Kavu': [],
    'Kochareekkal Caves': [],
    'Kochi Biennale': [],
    'Kochi Metro': [],
    'Kochi Water Metro': [],
    'Kodanad Elephant Training Centre': [],
    'Kodikuthimala': [],
    'Koonankurishu Church': [],
    'Koorumala': [],
    'Kothamangalam': [],
    'Kulippara Waterfalls': [],
    'Kumbalam': [],
    'Kumbalanghi': [],
    'Kundannoor': [],
    'Kuttippara Waterfalls': [],
    'Kuzhuppilly Beach': [],
    'Lazza iDrive': [],
    'Little Flower Church': [],
    'LuLu Mall': [],
    'Malayattoor Church': [],
    'Mamalakandam View Point': [],
    'Manappattu Chira': [],
    'Mangalathu Kavu Bhagavathi Temple': [],
    'Mangalavanam Bird Sanctuary': [],
    'Maniyanthiram Hill Top': [],
    'Maradu': [],
    'Marine Drive': [],
    'Marottichuvadu Waterfalls': [],
    'Mattancherry': [],
    'Mattancherry Palace': [],
    'Meekunnam Waterfalls': [],
    'Moolampilly Islands': [],
    'Mulavukad': [],
    'Munambam Beach': [],
    'Munippara Waterfalls': [],
    'Muniyara Cave': [],
    'Museum of Kerala History': [],
    'Muvattupuzha': [],
    'Nadukani View Point': [],
    'Nakshathra Vanam': [],
    'National Marine Biodiversity Museum': [],
    'Nedumbassery': [],
    'Nettoor': [],
    'Njarackal Arattuvazhi Beach': [],
    'North Paravur': [],
    'Ooranattu Chira': [],
    'Pachalam': [],
    'Padivattom': [],
    'Palarivattom': [],
    'Palliam Palace': [],
    'Pallikara': [],
    'Pallikkara Church': [],
    'Pallipuram Fort': [],
    'Palluruthy': [],
    'Panampilly Nagar': [],
    'Panampilly Nagar Central Park': [],
    'Panangad': [],
    'Panangad Jetty': [],
    'Paniyeli Poru': [],
    'Paradesi Synagogue': [],
    'Paravur': [],
    'Parikshit Thampuram Museum': [],
    'Pavamkulangara Devi Temple': [],
    'Pazhangad Beach': [],
    'Pazhoor': [],
    'Peechattu Mala': [],
    'Periyar Lake': [],
    'Periyar Wildlife Sanctuary': [],
    'Perumbavoor': [],
    'Pettamala': [],
    'Pindimedu Waterfalls': [],
    'Poonithura': [],
    'Puliyanipara View Point': [],
    'Puliyanpara View Point': [],
    'Puthenthode Beach': [],
    'Puthenvelikkara': [],
    'Puthuvype Beach': [],
    'Puthuvype Lighthouse Beach': [],
    'Queens Walkway': [],
    'Rainbow Hanging Bridge': [],
    'Rosary Park Vallarpadam': [],
    'Santa Cruz Cathedral Basilica': [],
    'Science Park Kalamassery': [],
    'Shoolam Waterfalls': [],
    'Sree Murugan Temple': [],
    'Sree Poornathrayeesa Temple': [],
    'Sreekrishna Swamy Temple': [],
    'St. Francis Church': [],
    'Streetscape Panampilly Nagar': [],
    'Subhash Bose Park': [],
    'Synodal Museum': [],
    'Thamaramkulangara Temple': [],
    'Thammanam': [],
    'Thattekkadu Bird Sanctuary': [],
    'Thattekkadu': [],
    'Thevara Ferry View Point': [],
    'Thirubali Waterfalls': [],
    'Thiruvankulam': [],
    'Thonippara Waterfalls': [],
    'Thoppumpady': [],
    'Thrikkakara': [],
    'Thrikkakara Temple': [],
    'Thrikkariyoor Temple': [],
    'Tripunithura': [],
    'Triveni Sangamam': [],
    'Vadattupara Waterfalls': [],
    'Vaduthala': [],
    'Vaikom Mahadeva Temple': [],
    'Valanthakad River Drive': [],
    'Valappu Beach': [],
    'Valiyavattom Island': [],
    'Vallarpadam Church': [],
    'Vandambra Para': [],
    'Varapuzha': [],
    'Vasco da Gama Square': [],
    'Vazhachal Waterfalls': [],
    'Vazhakkulam': [],
    'Veeranpuzha': [],
    'vennala': [],
    'vypin':['vypin beach'],
    'vytilla':[],
    'willingdon island':[],
    'wonderla':[]
}